events {}
http {
    upstream gentrading_cluster {
        server app_nodo_1:80;
        server app_nodo_2:80;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://gentrading_cluster;
            proxy_set_header Host $host;
        }
    }
}
